require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AnimalHandbooksController do

  # This should return the minimal set of attributes required to create a valid
  # AnimalHandbook. As you add validations to AnimalHandbook, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AnimalHandbooksController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all animal_handbooks as @animal_handbooks" do
      animal_handbook = AnimalHandbook.create! valid_attributes
      get :index, {}, valid_session
      assigns(:animal_handbooks).should eq([animal_handbook])
    end
  end

  describe "GET show" do
    it "assigns the requested animal_handbook as @animal_handbook" do
      animal_handbook = AnimalHandbook.create! valid_attributes
      get :show, {:id => animal_handbook.to_param}, valid_session
      assigns(:animal_handbook).should eq(animal_handbook)
    end
  end

  describe "GET new" do
    it "assigns a new animal_handbook as @animal_handbook" do
      get :new, {}, valid_session
      assigns(:animal_handbook).should be_a_new(AnimalHandbook)
    end
  end

  describe "GET edit" do
    it "assigns the requested animal_handbook as @animal_handbook" do
      animal_handbook = AnimalHandbook.create! valid_attributes
      get :edit, {:id => animal_handbook.to_param}, valid_session
      assigns(:animal_handbook).should eq(animal_handbook)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AnimalHandbook" do
        expect {
          post :create, {:animal_handbook => valid_attributes}, valid_session
        }.to change(AnimalHandbook, :count).by(1)
      end

      it "assigns a newly created animal_handbook as @animal_handbook" do
        post :create, {:animal_handbook => valid_attributes}, valid_session
        assigns(:animal_handbook).should be_a(AnimalHandbook)
        assigns(:animal_handbook).should be_persisted
      end

      it "redirects to the created animal_handbook" do
        post :create, {:animal_handbook => valid_attributes}, valid_session
        response.should redirect_to(AnimalHandbook.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved animal_handbook as @animal_handbook" do
        # Trigger the behavior that occurs when invalid params are submitted
        AnimalHandbook.any_instance.stub(:save).and_return(false)
        post :create, {:animal_handbook => {}}, valid_session
        assigns(:animal_handbook).should be_a_new(AnimalHandbook)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AnimalHandbook.any_instance.stub(:save).and_return(false)
        post :create, {:animal_handbook => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested animal_handbook" do
        animal_handbook = AnimalHandbook.create! valid_attributes
        # Assuming there are no other animal_handbooks in the database, this
        # specifies that the AnimalHandbook created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AnimalHandbook.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => animal_handbook.to_param, :animal_handbook => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested animal_handbook as @animal_handbook" do
        animal_handbook = AnimalHandbook.create! valid_attributes
        put :update, {:id => animal_handbook.to_param, :animal_handbook => valid_attributes}, valid_session
        assigns(:animal_handbook).should eq(animal_handbook)
      end

      it "redirects to the animal_handbook" do
        animal_handbook = AnimalHandbook.create! valid_attributes
        put :update, {:id => animal_handbook.to_param, :animal_handbook => valid_attributes}, valid_session
        response.should redirect_to(animal_handbook)
      end
    end

    describe "with invalid params" do
      it "assigns the animal_handbook as @animal_handbook" do
        animal_handbook = AnimalHandbook.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AnimalHandbook.any_instance.stub(:save).and_return(false)
        put :update, {:id => animal_handbook.to_param, :animal_handbook => {}}, valid_session
        assigns(:animal_handbook).should eq(animal_handbook)
      end

      it "re-renders the 'edit' template" do
        animal_handbook = AnimalHandbook.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AnimalHandbook.any_instance.stub(:save).and_return(false)
        put :update, {:id => animal_handbook.to_param, :animal_handbook => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested animal_handbook" do
      animal_handbook = AnimalHandbook.create! valid_attributes
      expect {
        delete :destroy, {:id => animal_handbook.to_param}, valid_session
      }.to change(AnimalHandbook, :count).by(-1)
    end

    it "redirects to the animal_handbooks list" do
      animal_handbook = AnimalHandbook.create! valid_attributes
      delete :destroy, {:id => animal_handbook.to_param}, valid_session
      response.should redirect_to(animal_handbooks_url)
    end
  end

end
